// <auto-generated />
using CodeFirstBasic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFirstBasic.Data.Migrations
{
    [DbContext(typeof(PatikaFirstDbContext))]
    partial class PatikaFirstDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstBasic.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Witcher 3: Wild Hunt",
                            Platform = "PC",
                            Rating = 9.3m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cyberpunk 2077",
                            Platform = "PC",
                            Rating = 6.9m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red Dead Redemption 2",
                            Platform = "PC",
                            Rating = 9.5m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grand Theft Auto V",
                            Platform = "PC",
                            Rating = 9.6m
                        },
                        new
                        {
                            Id = 5,
                            Name = "The Elder Scrolls V: Skyrim",
                            Platform = "PC",
                            Rating = 9.3m
                        });
                });

            modelBuilder.Entity("CodeFirstBasic.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Drama",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Crime",
                            ReleaseYear = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Adventure",
                            ReleaseYear = 2003,
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Crime",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
